import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import { Locale } from "@/i18n/routing";
import { getMessages } from "next-intl/server";
import { Suspense } from "react";
import { NextIntlClientProvider } from "next-intl";
import ReduxProvider from "@/providers/redux-provider";
import { Toaster } from "sonner";
import Loading from "./loading";
import DashboardLayout from "@/components/shared/DashboardLayout";

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Elkhodr Autocars",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{
    locale: Locale;
  }>;
}>) {
  const { locale } = await params;
  const messages = await getMessages();

  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <body className="antialiased bg-gray-100">
        <Suspense fallback={<Loading />}>
          <NextIntlClientProvider messages={messages}>
            <ReduxProvider>
              {children}
              <Toaster />
            </ReduxProvider>
          </NextIntlClientProvider>
        </Suspense>
      </body>
    </html>
  );
}
